name: ml_lecture
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.2.2
  - jupyterlab=3.1.7
  - matplotlib=3.4.2
  - numpy=1.20.3
  - pandas=1.3.3
  - seaborn=0.11.2
  - tensorflow=2.3.0
  - xgboost=1.5.0
  - plotly=5.6.0
  - scikit-learn=1.0.2
  - pip:
    - plotnine==0.8.0
    - dalex==1.4.1
    - lightgbm==3.3.2
    - nb-black==1.0.7

